#!/usr/bin/env bash
# Email a rendered shipreport file to a non-technical manager.
#
# Why this exists: shipreport produces files in out/; it does not
# deliver. This is the simplest end-to-end glue — drop a file into an
# email and send to a single recipient. Air-gapped-friendly: it dispatches
# through whichever local mail transport you have (msmtp / sendmail /
# mail / mailx). No public Internet required if your SMTP relay is
# internal.
#
# Usage:
#   scripts/email-report.sh --to <addr> --subject <line> --file <path>
#   scripts/email-report.sh --to <addr> --subject <line> --inline --file <html>
#   scripts/email-report.sh --pattern 'out/manager-rollup-*.pdf' \
#                          --managers managers.yaml
#
# Flags:
#   --to <addr>       Single recipient. Required unless --managers is used.
#   --subject <line>  Subject line. Required.
#   --file <path>     Single attachment / inline source file. Required
#                     unless --pattern is used.
#   --pattern <glob>  Glob expanding to one file per team; used with
#                     --managers to dispatch per-team automatically.
#   --managers <yaml> Sidecar YAML mapping `<team>: <email>`. The team
#                     name is parsed from the file path's
#                     `*-<team>-<quarter>.<ext>` portion.
#   --from <addr>     Sender. Default: $SHIPREPORT_FROM or
#                     `shipreport-bot@$(hostname -d)`.
#   --inline          For .html files, send the rendered body inline
#                     instead of as an attachment.
#   --dry-run         Print the message that would be sent; don't send.
#   --transport <bin> Force a transport (msmtp|sendmail|mail|mailx).
#                     Default: auto-detect.
#
# CONFIG: edit the section just below to point at your SMTP relay or
# leave it alone if your local /etc/msmtprc / sendmail config already
# routes mail correctly.

set -euo pipefail

# --- CONFIG ------------------------------------------------------------

# Override any of these in the environment OR by editing in place.
: "${SHIPREPORT_FROM:=shipreport-bot@$(hostname -d 2>/dev/null || hostname || echo localhost)}"
: "${SMTP_HOST:=smtp.your-corp.example}"   # Used only by the curl recipe at the bottom.
: "${SMTP_PORT:=587}"

# --- ARGS --------------------------------------------------------------

to=""
subject=""
file=""
pattern=""
managers_file="${MANAGERS_FILE:-}"
from="$SHIPREPORT_FROM"
inline=0
dry_run=0
transport=""

usage() {
  sed -n '2,33p' "$0"
  exit "$1"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --to)        to="$2"; shift 2;;
    --subject)   subject="$2"; shift 2;;
    --file)      file="$2"; shift 2;;
    --pattern)   pattern="$2"; shift 2;;
    --managers)  managers_file="$2"; shift 2;;
    --from)      from="$2"; shift 2;;
    --inline)    inline=1; shift;;
    --dry-run)   dry_run=1; shift;;
    --transport) transport="$2"; shift 2;;
    -h|--help)   usage 0;;
    *) echo "unknown arg: $1" >&2; usage 2;;
  esac
done

[[ -z "$subject" ]] && { echo "--subject required" >&2; exit 2; }

# --- TRANSPORT DETECTION ----------------------------------------------

detect_transport() {
  for t in msmtp sendmail mail mailx; do
    if command -v "$t" >/dev/null 2>&1; then echo "$t"; return; fi
  done
  return 1
}

if [[ -z "$transport" ]]; then
  if ! transport="$(detect_transport)"; then
    if [[ "$dry_run" -eq 1 ]]; then
      transport="(none — dry-run)"
    else
      cat >&2 <<EOF
No mail transport found on PATH (looked for msmtp, sendmail, mail,
mailx). Install one of:

  Debian/Ubuntu:  apt install msmtp msmtp-mta
  RHEL/Fedora:    dnf install msmtp
  Alpine:         apk add msmtp
  macOS:          brew install msmtp

…or pass --transport <bin> if your transport is non-standard, or use
the curl/Python recipe at the bottom of docs/16-delivery.md.
EOF
      exit 3
    fi
  fi
fi

# --- HELPERS ----------------------------------------------------------

# Build a MIME message with one attachment OR a single text/html body.
build_message() {
  local _to="$1"
  local _subject="$2"
  local _file="$3"
  local _inline="$4"
  local boundary="==SHIPREPORT_$(date +%s)_$$"

  printf 'From: %s\r\n'    "$from"
  printf 'To: %s\r\n'      "$_to"
  printf 'Subject: %s\r\n' "$_subject"
  printf 'MIME-Version: 1.0\r\n'

  if [[ "$_inline" -eq 1 && "$_file" == *.html ]]; then
    printf 'Content-Type: text/html; charset=utf-8\r\n'
    printf '\r\n'
    cat "$_file"
    return
  fi

  printf 'Content-Type: multipart/mixed; boundary="%s"\r\n' "$boundary"
  printf '\r\n'
  printf -- '--%s\r\n' "$boundary"
  printf 'Content-Type: text/plain; charset=utf-8\r\n'
  printf '\r\n'
  printf 'See attached: %s\r\n\r\n' "$(basename "$_file")"
  printf 'Generated by shipreport. Do not reply.\r\n\r\n'
  printf -- '--%s\r\n' "$boundary"
  case "$_file" in
    *.pdf)  printf 'Content-Type: application/pdf\r\n';;
    *.html) printf 'Content-Type: text/html; charset=utf-8\r\n';;
    *.png)  printf 'Content-Type: image/png\r\n';;
    *.md)   printf 'Content-Type: text/markdown; charset=utf-8\r\n';;
    *)      printf 'Content-Type: application/octet-stream\r\n';;
  esac
  printf 'Content-Transfer-Encoding: base64\r\n'
  printf 'Content-Disposition: attachment; filename="%s"\r\n' "$(basename "$_file")"
  printf '\r\n'
  base64 < "$_file"
  printf '\r\n--%s--\r\n' "$boundary"
}

send_one() {
  local _to="$1"
  local _file="$2"
  if [[ ! -f "$_file" ]]; then
    echo "  skip: $_file not found" >&2
    return 1
  fi
  if [[ "$dry_run" -eq 1 ]]; then
    echo "  would send: to=$_to subject='$subject' file=$_file transport=$transport"
    return 0
  fi
  echo "  sending: to=$_to file=$_file via $transport"
  case "$transport" in
    msmtp|sendmail)
      build_message "$_to" "$subject" "$_file" "$inline" | "$transport" -t
      ;;
    mail|mailx)
      # mail/mailx don't accept raw MIME on stdin reliably across
      # implementations; use their attachment flag if present.
      if "$transport" -h 2>&1 | grep -qE '\-A|\-a '; then
        echo "Generated by shipreport. Do not reply." | \
          "$transport" -s "$subject" -a "$_file" "$_to"
      else
        # Last-resort: rebuild MIME and pipe.
        build_message "$_to" "$subject" "$_file" "$inline" | "$transport" "$_to"
      fi
      ;;
    *)
      echo "unknown transport: $transport" >&2; return 4;;
  esac
}

# --- DISPATCH ---------------------------------------------------------

if [[ -n "$pattern" ]]; then
  [[ -z "$managers_file" ]] && {
    echo "--pattern requires --managers <yaml>" >&2; exit 2; }
  [[ ! -f "$managers_file" ]] && {
    echo "$managers_file not found" >&2; exit 2; }

  # shellcheck disable=SC2086  # intentional glob expansion
  for f in $pattern; do
    [[ -e "$f" ]] || continue
    # Extract team name from `*-<team>-<quarter>.<ext>`.
    base="$(basename "$f")"
    # Strip extension, then strip the trailing `-<quarter>`.
    name="${base%.*}"
    name="${name%-*}"          # strip -<quarter>
    team="${name#manager-rollup-}"
    team="${team#team-summary-}"
    addr="$(awk -v t="$team:" '$1==t {print $2}' "$managers_file")"
    if [[ -z "$addr" ]]; then
      echo "  skip: no manager email for team '$team' in $managers_file" >&2
      continue
    fi
    send_one "$addr" "$f" || true
  done
else
  [[ -z "$to"   ]] && { echo "--to or --pattern+--managers required" >&2; exit 2; }
  [[ -z "$file" ]] && { echo "--file required" >&2; exit 2; }
  send_one "$to" "$file"
fi
